import "./styles.css";

const cfg={"n":"01","title":"State Garden","kind":"state","slug":"state-garden","site":"gdv502-p01-state-garden","objective":"Implement explicit game states; separate input, update, and rendering concerns; handle transitions reliably.","execution":"A cheerful orchard arcade game with menu, countdown, play, pause, game-over, and results states. A visible state rail and debug log prove every transition.","rubric":"30 pts state architecture; 20 pts gameplay completeness; 20 pts transition reliability; 15 pts code readability; 15 pts debug/test documentation.","controls":"Space start/dash, arrows/WASD move, P pause, D debug","palette":["#fff7d8","#20311f","#5fb36a","#ed9b40","#dc5b57","#6bb7c8"]};
const canvas=document.querySelector("#game");
const ctx=canvas.getContext("2d");
const W=1120,H=700,TAU=Math.PI*2;
const keys=new Set();
const pointer={x:W/2,y:H/2,down:false,tapped:false};
let last=0;
let saveOk=true;
const state={mode:"menu",time:0,score:0,message:cfg.execution,debug:false,log:[],game:{}};
const samples=["0000000000000000000000000000000000000000000000000000000000000000","0111110010000100101101001000010010110100100001001111100000000000","0100010010110100100011001011001001000100101111000000000000000000"];

function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function dist(a,b,c,d){return Math.hypot(a-c,b-d)}
function rnd(seed){const x=Math.sin(seed*999.37)*43758.5453;return x-Math.floor(x)}
function addLog(text){state.log.unshift(text);state.log=state.log.slice(0,7)}
function key(...codes){return codes.some(c=>keys.has(c))}
function circle(x,y,r,fill,stroke){ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke()}}
function rect(x,y,w,h,fill,stroke){ctx.fillStyle=fill;ctx.fillRect(x,y,w,h);if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.strokeRect(x,y,w,h)}}
function text(t,x,y,size=18,color=cfg.palette[1],weight=700,align="left"){ctx.fillStyle=color;ctx.font=weight+" "+size+"px Inter, Segoe UI, sans-serif";ctx.textAlign=align;ctx.textBaseline="alphabetic";ctx.fillText(t,x,y)}
function wrap(t,x,y,w,lh,size=18,color=cfg.palette[1],weight=650){ctx.font=weight+" "+size+"px Inter, Segoe UI, sans-serif";let line="";for(const word of String(t).split(" ")){const test=line?line+" "+word:word;if(ctx.measureText(test).width>w&&line){text(line,x,y,size,color,weight);line=word;y+=lh}else line=test}if(line)text(line,x,y,size,color,weight)}
function button(x,y,w,h,label,fill="#fff"){rect(x,y,w,h,fill,"rgba(32,49,31,.24)");text(label,x+w/2,y+h/2+6,15,cfg.palette[1],850,"center")}
function player(){return state.game.p}
function movePlayer(dt,speed=220){const p=player();let dx=(key("ArrowRight","KeyD")?1:0)-(key("ArrowLeft","KeyA")?1:0);let dy=(key("ArrowDown","KeyS")?1:0)-(key("ArrowUp","KeyW")?1:0);if(dx||dy){const m=Math.hypot(dx,dy);dx/=m;dy/=m}p.x=clamp(p.x+dx*speed*dt,56,1040);p.y=clamp(p.y+dy*speed*dt,96,610)}
function start(){state.mode=cfg.kind==="state"?"countdown":"play";state.time=0;state.score=0;state.log=[];initKind();addLog("Started "+cfg.title)}
function finish(message){state.mode="complete";state.message=message;addLog(message)}
function reset(){state.mode="menu";state.time=0;state.score=0;state.log=[];state.message=cfg.execution;state.game={}}

function initKind(){
  const k=cfg.kind;
  if(k==="state")state.game={phase:"countdown",count:3,p:{x:160,y:360,r:16},stars:[],bugs:[],survive:0,stateLog:["menu -> countdown"]};
  if(k==="collision")state.game={p:{x:150,y:350,r:18,vx:0,vy:0},debug:false,seeds:[0,1,2,3].map(i=>({x:360+i*90,y:180+rnd(i)*320,r:14,vx:0,vy:0,done:false})),pots:[{x:860,y:180},{x:940,y:360},{x:820,y:520}],bumpers:[{x:560,y:250,r:34},{x:655,y:430,r:42}]};
  if(k==="waves")state.game={p:{x:560,y:560,r:15},wave:0,timer:0,gust:0,kites:[],waves:[{name:"Blue ladders",count:4,speed:75,pattern:"line"},{name:"Gold zigzag",count:5,speed:95,pattern:"zig"},{name:"Crosswind",count:6,speed:105,pattern:"side"},{name:"Festival rush",count:8,speed:120,pattern:"rain"},{name:"Spiral tails",count:8,speed:135,pattern:"curve"},{name:"Final sky",count:10,speed:150,pattern:"mix"}]};
  if(k==="persistence")loadPersistent();
  if(k==="builder")state.game={mode:"edit",grid:Array(64).fill(0),p:{x:4,y:7},goal:{x:7,y:0},saved:"",sample:0};
  if(k==="procedural")makeProcedural(state.game.seed||"MEADOW-42");
  if(k==="remap")state.game={p:{x:120,y:360,r:16},target:{x:900,y:180},dashKey:"Space",interactKey:"KeyE",remap:null,deliveries:0,clickMove:null};
  if(k==="ai")state.game={p:{x:560,y:510,r:16},lamp:false,bell:0,nectar:[{x:260,y:220},{x:880,y:240},{x:620,y:380}],moths:[{x:260,y:470,node:"idle",target:0},{x:820,y:470,node:"idle",target:1}]};
  if(k==="performance")state.game={p:{x:560,y:350,r:18},optimized:true,particles:[],pool:[],fps:60,lastCost:0,spawned:0};
  if(k==="kit")state.game={p:{x:120,y:520,r:16,hp:5},items:[],ability:0,timer:75,spawn:0,dialogue:"Find key, brew tea, open the green gate.",components:[]};
}

function loadPersistent(){let data;try{data=JSON.parse(localStorage.getItem("gdv502-p04")||"null");if(!data||!data.p||!Array.isArray(data.stamps))throw new Error("bad save");saveOk=true}catch{data={p:{x:130,y:520,r:16},stamps:[],contrast:false,best:0};saveOk=false}state.game={...data,stampsAll:[{x:260,y:180,id:"north"},{x:780,y:160,id:"east"},{x:940,y:520,id:"harbor"},{x:450,y:430,id:"market"}]};state.message=saveOk?"Save loaded. Collect lantern stamps; every pickup persists.":"Save fallback used. Corrupt or missing save was safely replaced."}
function savePersistent(){const g=state.game;localStorage.setItem("gdv502-p04",JSON.stringify({p:g.p,stamps:g.stamps,contrast:g.contrast,best:Math.max(g.best||0,g.stamps.length)}))}
function makeProcedural(seed){let hash=0;for(const ch of seed)hash=(hash*31+ch.charCodeAt(0))|0;const fruit=[],hazards=[];for(let i=0;i<10;i++)fruit.push({x:140+rnd(hash+i)*820,y:120+rnd(hash+i+40)*440,taken:false});for(let i=0;i<7;i++)hazards.push({x:180+rnd(hash+i+80)*760,y:130+rnd(hash+i+120)*430,r:22+rnd(hash+i+3)*16});state.game={seed,p:{x:90,y:560,r:15},exit:{x:1010,y:120},fruit,hazards,wind:[{x:350,y:120,w:38,h:430,dy:-1},{x:690,y:180,w:38,h:410,dy:1}]};state.message="Seed "+seed+" generated. The same replay code always recreates this orchard."}

function update(dt){
  if(state.mode==="menu"||state.mode==="complete")return;
  state.time+=dt;
  const k=cfg.kind,g=state.game;
  if(k==="state"){if(state.mode==="countdown"){g.count-=dt;if(g.count<=0){state.mode="play";g.stateLog.push("countdown -> play");addLog("PLAY state")}}else{movePlayer(dt,230);g.survive+=dt;if(Math.floor(state.time*1.4)!==Math.floor((state.time-dt)*1.4))g.stars.push({x:120+rnd(state.time)*850,y:120+rnd(state.time+9)*430});if(Math.floor(state.time*.8)!==Math.floor((state.time-dt)*.8))g.bugs.push({x:1050,y:120+rnd(state.time+5)*450,v:85+rnd(state.time+3)*80});g.bugs.forEach(b=>b.x-=b.v*dt);g.stars=g.stars.filter(s=>{if(dist(g.p.x,g.p.y,s.x,s.y)<28){state.score+=20;return false}return true});if(g.bugs.some(b=>dist(g.p.x,g.p.y,b.x,b.y)<28))finish("Results: survived "+g.survive.toFixed(1)+"s, score "+state.score+".");}}
  if(k==="collision"){const p=g.p;let ax=((key("ArrowRight","KeyD")?1:0)-(key("ArrowLeft","KeyA")?1:0))*520,ay=((key("ArrowDown","KeyS")?1:0)-(key("ArrowUp","KeyW")?1:0))*520;p.vx=(p.vx+ax*dt)*.94;p.vy=(p.vy+ay*dt)*.94;p.x=clamp(p.x+p.vx*dt,45,1075);p.y=clamp(p.y+p.vy*dt,90,620);for(const s of g.seeds){if(s.done)continue;if(dist(p.x,p.y,s.x,s.y)<p.r+s.r){const a=Math.atan2(s.y-p.y,s.x-p.x);s.vx+=Math.cos(a)*150;s.vy+=Math.sin(a)*150}for(const b of g.bumpers){if(dist(s.x,s.y,b.x,b.y)<s.r+b.r){const a=Math.atan2(s.y-b.y,s.x-b.x);s.vx+=Math.cos(a)*120;s.vy+=Math.sin(a)*120}}s.x=clamp(s.x+s.vx*dt,50,1070);s.y=clamp(s.y+s.vy*dt,100,610);s.vx*=.96;s.vy*=.96;for(const pot of g.pots)if(dist(s.x,s.y,pot.x,pot.y)<32&&!s.done){s.done=true;state.score+=50;addLog("Seed planted")}}if(g.seeds.every(s=>s.done))finish("All seeds planted with clean collision rules.");}
  if(k==="waves"){movePlayer(dt,235);if(g.gust>0)g.gust-=dt;g.timer-=dt;if(g.timer<=0){const w=g.waves[g.wave%g.waves.length];addLog("Wave "+(g.wave+1)+": "+w.name);for(let i=0;i<w.count;i++)g.kites.push({x:100+rnd(g.wave*20+i)*900,y:80-rnd(i)*120,v:w.speed,pat:w.pattern,a:rnd(i+g.wave)*TAU});g.timer=5;g.wave++}g.kites.forEach(o=>{o.y+=o.v*dt;o.x+=Math.sin(state.time*2+o.a)*(o.pat==="zig"?80:25)*dt;if(g.gust>0)o.y-=120*dt});g.kites=g.kites.filter(o=>o.y<660);if(g.kites.some(o=>dist(g.p.x,g.p.y,o.x,o.y)<28))finish("Kite clipped the runner after "+state.score+" parade points.");state.score+=dt*5;if(g.wave>=6&&g.kites.length===0)finish("All six data-authored waves cleared.");}
  if(k==="persistence"){movePlayer(dt,210);for(const st of g.stampsAll){if(!g.stamps.includes(st.id)&&dist(g.p.x,g.p.y,st.x,st.y)<30){g.stamps.push(st.id);state.score=g.stamps.length*25;addLog("Saved stamp: "+st.id);savePersistent()}}if(g.stamps.length===4)finish("Atlas complete. Save contains position, settings, stamps, and best count.")}
  if(k==="builder"){if(g.mode==="play"){let dx=(key("ArrowRight","KeyD")?1:0)-(key("ArrowLeft","KeyA")?1:0),dy=(key("ArrowDown","KeyS")?1:0)-(key("ArrowUp","KeyW")?1:0);if((dx||dy)&&!g.cool){const nx=clamp(g.p.x+dx,0,7),ny=clamp(g.p.y+dy,0,7);if(g.grid[ny*8+nx]===0){g.p.x=nx;g.p.y=ny}g.cool=.15}g.cool=Math.max(0,(g.cool||0)-dt);if(g.p.x===g.goal.x&&g.p.y===g.goal.y)finish("Designer level validated in play mode.")}}
  if(k==="procedural"){movePlayer(dt,220);for(const lane of g.wind)if(g.p.x>lane.x&&g.p.x<lane.x+lane.w&&g.p.y>lane.y&&g.p.y<lane.y+lane.h)g.p.y=clamp(g.p.y+lane.dy*90*dt,96,610);g.fruit.forEach(f=>{if(!f.taken&&dist(g.p.x,g.p.y,f.x,f.y)<25){f.taken=true;state.score+=15}});if(g.hazards.some(h=>dist(g.p.x,g.p.y,h.x,h.y)<g.p.r+h.r))finish("Run ended on seed "+g.seed+" with "+state.score+" fruit points.");if(dist(g.p.x,g.p.y,g.exit.x,g.exit.y)<32)finish("Seed "+g.seed+" cleared with "+state.score+" points.")}
  if(k==="remap"){if(g.clickMove){const a=Math.atan2(g.clickMove.y-g.p.y,g.clickMove.x-g.p.x);g.p.x+=Math.cos(a)*210*dt;g.p.y+=Math.sin(a)*210*dt;if(dist(g.p.x,g.p.y,g.clickMove.x,g.clickMove.y)<12)g.clickMove=null}else movePlayer(dt,210);if(dist(g.p.x,g.p.y,g.target.x,g.target.y)<28){g.deliveries++;state.score+=40;g.target={x:120+rnd(g.deliveries)*880,y:120+rnd(g.deliveries+2)*450};addLog("Parcel delivered via abstract input.")}if(g.deliveries>=5)finish("Five deliveries completed with remappable actions.")}
  if(k==="ai"){movePlayer(dt,210);g.bell=Math.max(0,g.bell-dt);for(const m of g.moths){const lampDanger=g.lamp&&dist(m.x,m.y,g.p.x,g.p.y)<220;const food=g.nectar[m.target%g.nectar.length];if(lampDanger)m.node="flee-lamp";else if(g.bell>0)m.node="investigate-bell";else if(dist(m.x,m.y,food.x,food.y)>20)m.node="forage";else{m.node="share-nectar";m.target++;state.score+=5}let tx=m.node==="flee-lamp"?W-g.p.x:m.node==="investigate-bell"?g.p.x:food.x,ty=m.node==="flee-lamp"?H-g.p.y:m.node==="investigate-bell"?g.p.y:food.y;const a=Math.atan2(ty-m.y,tx-m.x);m.x+=Math.cos(a)*110*dt;m.y+=Math.sin(a)*110*dt}if(state.score>=80)finish("Behavior tree demo complete: forage, investigate, flee, assist.")}
  if(k==="performance"){const now=performance.now();g.lastCost=0;const target=key("Space")?120:20;for(let i=0;i<target;i++){const p=g.optimized&&(g.pool.pop()||{});const obj=p||{};obj.x=g.p.x;obj.y=g.p.y;obj.vx=(rnd(state.time+i)-.5)*220;obj.vy=(rnd(state.time+i+4)-.5)*220;obj.life=1.4;g.particles.push(obj);g.spawned++}if(pointer.down){g.p.x=pointer.x;g.p.y=pointer.y}g.particles=g.particles.filter(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(p.life<=0){if(g.optimized)g.pool.push(p);return false}return true});g.fps=1/dt;g.lastCost=performance.now()-now;state.score=Math.max(state.score,g.particles.length);if(g.spawned>4000)finish("Performance budget demonstrated with "+g.particles.length+" active petals and pooling="+g.optimized+".")}
  if(k==="kit"){movePlayer(dt,205);g.timer-=dt;g.ability=Math.max(0,g.ability-dt);g.spawn-=dt;if(g.spawn<=0){g.spawn=4;g.components.unshift("Spawner emitted a soft hazard.")}if(dist(g.p.x,g.p.y,360,280)<34&&!g.items.includes("key")){g.items.push("key");g.components.unshift("Inventory added key.")}if(dist(g.p.x,g.p.y,620,360)<34&&!g.items.includes("tea")){g.items.push("tea");g.components.unshift("Interactable brewed tea.")}if(g.items.includes("key")&&g.items.includes("tea")&&dist(g.p.x,g.p.y,930,230)<42)finish("Prototype kit adventure complete. Components worked together.")}
}

function drawBackdrop(){
  const k=cfg.kind;
  const grad=ctx.createLinearGradient(0,0,W,H);grad.addColorStop(0,cfg.palette[0]);grad.addColorStop(1,"#fffefa");ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);
  ctx.save();
  if(k==="state"){ctx.fillStyle="#fffbe6";ctx.fillRect(395,76,645,548);for(let y=130;y<615;y+=64){ctx.strokeStyle="rgba(95,179,106,.2)";ctx.lineWidth=18;ctx.beginPath();ctx.moveTo(410,y);ctx.bezierCurveTo(560,y-45,760,y+45,1015,y-10);ctx.stroke()}for(let i=0;i<26;i++)circle(445+rnd(i)*555,118+rnd(i+80)*470,5+rnd(i+4)*15,i%3?cfg.palette[2]:cfg.palette[3])}
  if(k==="collision"){ctx.fillStyle="#f4fff8";ctx.fillRect(370,74,690,560);for(let i=0;i<9;i++){ctx.strokeStyle=i%2?"rgba(67,143,111,.16)":"rgba(232,150,76,.18)";ctx.lineWidth=2;circle(510+rnd(i)*430,130+rnd(i+9)*430,44+i*13,"transparent",ctx.strokeStyle)}for(let i=0;i<11;i++){rect(405+i*55,606-(i%4)*36,36,14,i%2?cfg.palette[3]:cfg.palette[5])}}
  if(k==="waves"){ctx.fillStyle="#effaff";ctx.fillRect(370,70,700,560);for(let y=120;y<560;y+=70){ctx.strokeStyle="rgba(91,164,210,.22)";ctx.beginPath();ctx.moveTo(390,y);for(let x=390;x<1045;x+=60)ctx.quadraticCurveTo(x+30,y-24,x+60,y);ctx.stroke()}for(let i=0;i<14;i++){ctx.fillStyle=i%2?cfg.palette[3]:cfg.palette[5];ctx.beginPath();ctx.moveTo(420+i*44,90);ctx.lineTo(442+i*44,124);ctx.lineTo(398+i*44,124);ctx.closePath();ctx.fill()}}
  if(k==="persistence"){ctx.fillStyle="#fff5d9";ctx.fillRect(382,70,675,560);ctx.strokeStyle="rgba(116,78,37,.24)";ctx.lineWidth=2;for(let i=0;i<8;i++){ctx.beginPath();ctx.moveTo(430+rnd(i)*560,120+rnd(i+3)*430);ctx.bezierCurveTo(520+rnd(i+8)*300,70+rnd(i+2)*520,720+rnd(i+9)*270,120+rnd(i+10)*440,980-rnd(i+13)*220,160+rnd(i+15)*380);ctx.stroke()}for(let i=0;i<6;i++){circle(460+rnd(i)*520,140+rnd(i+20)*430,22,"rgba(237,155,64,.14)","rgba(116,78,37,.22)")}}
  if(k==="builder"){ctx.fillStyle="#fffaf1";ctx.fillRect(374,72,684,558);for(let x=390;x<1040;x+=38){ctx.strokeStyle=x%76?"rgba(58,88,73,.1)":"rgba(58,88,73,.22)";ctx.beginPath();ctx.moveTo(x,88);ctx.lineTo(x,615);ctx.stroke()}for(let y=88;y<615;y+=38){ctx.strokeStyle=y%76?"rgba(58,88,73,.1)":"rgba(58,88,73,.22)";ctx.beginPath();ctx.moveTo(390,y);ctx.lineTo(1040,y);ctx.stroke()}rect(820,110,178,92,"rgba(209,91,90,.1)","rgba(209,91,90,.25)")}
  if(k==="procedural"){ctx.fillStyle="#f2ffeb";ctx.fillRect(372,70,690,560);for(let i=0;i<10;i++){ctx.strokeStyle=["rgba(75,151,93,.18)","rgba(237,155,64,.2)","rgba(91,164,210,.16)"][i%3];ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(690,350,90+i*35,46+i*23,(i%4)*.3,0,TAU);ctx.stroke()}for(let i=0;i<38;i++)rect(420+rnd(i)*580,115+rnd(i+30)*440,5,5,i%2?cfg.palette[2]:cfg.palette[3])}
  if(k==="remap"){ctx.fillStyle="#f8fbff";ctx.fillRect(374,70,690,560);ctx.strokeStyle="rgba(35,61,86,.18)";ctx.lineWidth=18;for(let i=0;i<6;i++){ctx.beginPath();ctx.moveTo(410,140+i*78);ctx.lineTo(1040,100+i*82);ctx.stroke()}ctx.lineWidth=12;for(let i=0;i<5;i++){ctx.beginPath();ctx.moveTo(470+i*112,86);ctx.lineTo(430+i*126,615);ctx.stroke()}for(let i=0;i<9;i++)rect(480+rnd(i)*480,130+rnd(i+5)*390,46,28,i%2?cfg.palette[3]:cfg.palette[5])}
  if(k==="ai"){ctx.fillStyle="#fbf7ff";ctx.fillRect(372,70,690,560);ctx.strokeStyle="rgba(102,91,166,.16)";for(let x=420;x<1040;x+=82){ctx.beginPath();ctx.moveTo(x,86);ctx.lineTo(x-70,615);ctx.stroke()}for(let y=110;y<610;y+=82){ctx.beginPath();ctx.moveTo(390,y);ctx.lineTo(1050,y+26);ctx.stroke()}for(let i=0;i<18;i++)circle(440+rnd(i)*560,120+rnd(i+8)*420,8+rnd(i)*18,i%2?cfg.palette[5]:cfg.palette[3])}
  if(k==="performance"){ctx.fillStyle="#fff6fb";ctx.fillRect(372,70,690,560);for(let x=400;x<1040;x+=32){ctx.strokeStyle="rgba(178,73,122,.08)";ctx.beginPath();ctx.moveTo(x,90);ctx.lineTo(x,615);ctx.stroke()}for(let y=100;y<615;y+=32){ctx.beginPath();ctx.moveTo(390,y);ctx.lineTo(1040,y);ctx.stroke()}ctx.strokeStyle=cfg.palette[4];ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(420,520);for(let x=420;x<1030;x+=18)ctx.lineTo(x,500-Math.sin(x*.05)*50-rnd(x)*80);ctx.stroke()}
  if(k==="kit"){ctx.fillStyle="#f3fbf1";ctx.fillRect(372,70,690,560);ctx.strokeStyle="rgba(42,96,60,.18)";ctx.lineWidth=2;for(let i=0;i<7;i++){rect(430+i*82,120+(i%3)*75,58,58,"rgba(255,255,255,.52)",ctx.strokeStyle);circle(459+i*82,149+(i%3)*75,12,i%2?cfg.palette[2]:cfg.palette[3])}ctx.setLineDash([8,8]);ctx.beginPath();ctx.moveTo(430,540);ctx.lineTo(965,155);ctx.stroke();ctx.setLineDash([])}
  ctx.restore();
}

function drawShell(){
  drawBackdrop();
  rect(28,28,330,624,"rgba(255,255,255,.78)","rgba(32,49,31,.18)");
  ctx.strokeStyle="rgba(32,49,31,.22)";ctx.lineWidth=2;ctx.strokeRect(28,28,W-56,H-56);
  text("GDV502-P"+cfg.n,54,58,14,cfg.palette[2],900);text(cfg.title,54,96,34,cfg.palette[1],900);wrap(state.message,54,130,270,24,16,"rgba(38,49,36,.72)",650);text("Score "+Math.round(state.score),54,252,18,cfg.palette[2],900);wrap(cfg.controls,54,600,270,22,15,cfg.palette[1],800);
  state.log.forEach((l,i)=>text(l,790,520+i*23,13,"rgba(38,49,36,.68)",650));
}

function render(){
  drawShell();
  if(state.mode==="menu"){rect(420,220,560,300,"rgba(255,255,255,.86)","rgba(32,49,31,.22)");wrap(cfg.execution,460,288,480,30,24,cfg.palette[1],850);button(460,455,180,54,"Start",cfg.palette[0]);text("Press Space or click Start",665,488,18,cfg.palette[2],850);return}
  if(state.mode==="countdown"){renderState();text(Math.ceil(state.game.count),615,375,96,cfg.palette[3],900,"center");return}
  if(cfg.kind==="state")renderState(); if(cfg.kind==="collision")renderCollision(); if(cfg.kind==="waves")renderWaves(); if(cfg.kind==="persistence")renderPersistence(); if(cfg.kind==="builder")renderBuilder(); if(cfg.kind==="procedural")renderProcedural(); if(cfg.kind==="remap")renderRemap(); if(cfg.kind==="ai")renderAI(); if(cfg.kind==="performance")renderPerformance(); if(cfg.kind==="kit")renderKit();
  if(state.mode==="pause"){rect(430,250,460,160,"rgba(255,255,255,.9)",cfg.palette[3]);text("Paused",500,330,42,cfg.palette[1],900);text("Press P to resume",500,370,18,cfg.palette[2],850)}
  if(state.mode==="complete"){rect(360,235,520,230,"rgba(255,255,255,.92)",cfg.palette[3]);wrap(state.message,405,305,430,34,26,cfg.palette[1],900);text("Press R to restart",405,410,18,cfg.palette[2],900)}
}

function renderState(){const g=state.game,p=g.p;circle(p.x,p.y,p.r,cfg.palette[2]);(g.stars||[]).forEach(s=>circle(s.x,s.y,10,cfg.palette[3]));(g.bugs||[]).forEach(b=>rect(b.x-13,b.y-13,26,26,cfg.palette[4]));["menu","countdown","play","pause","results"].forEach((name,i)=>{rect(430+i*105,130,90,30,state.mode===name||g.phase===name?cfg.palette[3]:"rgba(255,255,255,.72)","rgba(32,49,31,.18)");text(name,475+i*105,151,12,cfg.palette[1],800,"center")});if(state.debug||g.stateLog)wrap((g.stateLog||[]).slice(-4).join(" / "),430,182,520,22,14,cfg.palette[2],750)}
function renderCollision(){const g=state.game,p=g.p;g.pots.forEach(o=>circle(o.x,o.y,38,"rgba(255,255,255,.72)",cfg.palette[3]));g.bumpers.forEach(b=>circle(b.x,b.y,b.r,"rgba(214,95,119,.18)",cfg.palette[4]));g.seeds.forEach(s=>circle(s.x,s.y,s.r,s.done?cfg.palette[2]:cfg.palette[3]));circle(p.x,p.y,p.r,cfg.palette[5]);if(g.debug){[p,...g.seeds].forEach(o=>{ctx.strokeStyle=cfg.palette[4];ctx.beginPath();ctx.moveTo(o.x,o.y);ctx.lineTo(o.x+(o.vx||0)*.3,o.y+(o.vy||0)*.3);ctx.stroke()})}text("Planted "+g.seeds.filter(s=>s.done).length+"/"+g.seeds.length+"   Debug "+(g.debug?"on":"off"),430,128,18,cfg.palette[1],850)}
function renderWaves(){const g=state.game;circle(g.p.x,g.p.y,g.p.r,cfg.palette[2]);g.kites.forEach(o=>{circle(o.x,o.y,16,cfg.palette[3]);ctx.strokeStyle=cfg.palette[5];ctx.beginPath();ctx.moveTo(o.x,o.y+12);ctx.lineTo(o.x-20,o.y+40);ctx.stroke()});rect(430,112,360*(g.timer/5),12,cfg.palette[3]);text("Wave "+Math.min(g.wave+1,6)+"/6  "+(g.waves[g.wave%g.waves.length]?.name||"clear"),430,150,18,cfg.palette[1],850)}
function renderPersistence(){const g=state.game;circle(g.p.x,g.p.y,g.p.r,g.contrast?cfg.palette[4]:cfg.palette[2]);g.stampsAll.forEach(st=>circle(st.x,st.y,18,g.stamps.includes(st.id)?cfg.palette[3]:"rgba(255,255,255,.72)",cfg.palette[2]));text("Saved stamps "+g.stamps.length+"/4  Save "+(saveOk?"loaded":"fallback")+"  Contrast "+(g.contrast?"on":"off"),430,128,18,cfg.palette[1],850)}
function renderBuilder(){const g=state.game,cell=46,ox=470,oy=150;for(let y=0;y<8;y++)for(let x=0;x<8;x++){const v=g.grid[y*8+x];rect(ox+x*cell,oy+y*cell,cell-3,cell-3,v?cfg.palette[4]:"rgba(255,255,255,.72)","rgba(32,49,31,.12)")}rect(ox+g.goal.x*cell+9,oy+g.goal.y*cell+9,28,28,cfg.palette[3]);circle(ox+g.p.x*cell+23,oy+g.p.y*cell+23,14,cfg.palette[2]);text("Mode "+g.mode+"   code "+(g.saved||"unsaved"),430,128,18,cfg.palette[1],850)}
function renderProcedural(){const g=state.game;g.wind.forEach(w=>rect(w.x,w.y,w.w,w.h,"rgba(116,169,216,.16)",cfg.palette[5]));g.hazards.forEach(h=>circle(h.x,h.y,h.r,"rgba(196,86,71,.20)",cfg.palette[4]));g.fruit.forEach(f=>!f.taken&&circle(f.x,f.y,11,cfg.palette[3]));circle(g.exit.x,g.exit.y,32,"rgba(255,255,255,.75)",cfg.palette[2]);circle(g.p.x,g.p.y,g.p.r,cfg.palette[2]);text("Seed "+g.seed+"  Fruit "+g.fruit.filter(f=>f.taken).length+"/10",430,128,18,cfg.palette[1],850)}
function renderRemap(){const g=state.game;circle(g.target.x,g.target.y,24,cfg.palette[3]);circle(g.p.x,g.p.y,g.p.r,cfg.palette[2]);text("Deliveries "+g.deliveries+"/5",430,128,18,cfg.palette[1],850);button(430,160,210,42,"Dash: "+g.dashKey);button(660,160,230,42,"Interact: "+g.interactKey);if(g.remap)text("Press a key for "+g.remap,430,230,22,cfg.palette[4],900)}
function renderAI(){const g=state.game;g.nectar.forEach(n=>circle(n.x,n.y,18,cfg.palette[3]));circle(g.p.x,g.p.y,g.p.r,g.lamp?cfg.palette[4]:cfg.palette[2]);g.moths.forEach(m=>{circle(m.x,m.y,17,cfg.palette[5]);text(m.node,m.x-38,m.y-28,12,cfg.palette[1],800)});text("Lamp "+(g.lamp?"on":"off")+"  Bell "+g.bell.toFixed(1),430,128,18,cfg.palette[1],850)}
function renderPerformance(){const g=state.game;g.particles.forEach(p=>circle(p.x,p.y,3, cfg.palette[2]));circle(g.p.x,g.p.y,g.p.r,cfg.palette[4]);text("Active "+g.particles.length+"  Pool "+g.pool.length+"  Optimized "+g.optimized+"  Cost "+g.lastCost.toFixed(2)+"ms",430,128,18,cfg.palette[1],850)}
function renderKit(){const g=state.game;circle(g.p.x,g.p.y,g.p.r,cfg.palette[2]);circle(360,280,24,g.items.includes("key")?cfg.palette[3]:"rgba(255,255,255,.75)",cfg.palette[3]);circle(620,360,24,g.items.includes("tea")?cfg.palette[5]:"rgba(255,255,255,.75)",cfg.palette[5]);rect(900,190,70,70,g.items.includes("key")&&g.items.includes("tea")?cfg.palette[2]:"rgba(255,255,255,.7)",cfg.palette[2]);text("HP "+g.p.hp+"  Items "+g.items.join(", ")+"  Timer "+Math.ceil(g.timer),430,128,18,cfg.palette[1],850);g.components.slice(0,6).forEach((c,i)=>text(c,790,165+i*24,13,cfg.palette[1],700))}

function click(x,y){pointer.tapped=true;if(state.mode==="menu"){start();return}const g=state.game;if(cfg.kind==="builder"&&g.mode==="edit"){const cell=46,ox=470,oy=150;const gx=Math.floor((x-ox)/cell),gy=Math.floor((y-oy)/cell);if(gx>=0&&gx<8&&gy>=0&&gy<8){g.grid[gy*8+gx]=g.grid[gy*8+gx]?0:1}}if(cfg.kind==="remap")g.clickMove={x,y};if(cfg.kind==="performance"){g.p.x=x;g.p.y=y}}
function onKey(e,up=false){if(up){keys.delete(e.code);return}keys.add(e.code);if(state.game.remap){state.game[state.game.remap==="dash"?"dashKey":"interactKey"]=e.code;addLog("Remapped "+state.game.remap+" to "+e.code);state.game.remap=null;return}if(e.code==="Space"&&state.mode==="menu")start();if(e.code==="KeyR")start();if(e.code==="KeyP"&&cfg.kind==="state"){state.mode=state.mode==="pause"?"play":"pause";state.game.stateLog?.push(state.mode==="pause"?"play -> pause":"pause -> play")}if(e.code==="KeyD")state.debug=!state.debug;if(e.code==="KeyH"&&cfg.kind==="collision")state.game.debug=!state.game.debug;if(e.code==="Space"&&cfg.kind==="collision"){const p=player();p.vx*=1.4;p.vy*=1.4;addLog("Pulse applied")}if(e.code==="Space"&&cfg.kind==="waves")state.game.gust=.8;if(e.code==="KeyC"&&cfg.kind==="persistence"){state.game.contrast=!state.game.contrast;savePersistent()}if(e.code==="KeyX"&&cfg.kind==="persistence"){localStorage.setItem("gdv502-p04","not json");addLog("Corrupt save written; restart to test fallback.")}if(e.code==="Backspace"&&cfg.kind==="persistence"){localStorage.removeItem("gdv502-p04");start()}if(e.code==="KeyT"&&cfg.kind==="builder"){const g=state.game;g.mode=g.mode==="edit"?"play":"edit";g.p={x:0,y:7}}if(["Digit1","Digit2","Digit3"].includes(e.code)&&cfg.kind==="builder"){state.game.grid=samples[Number(e.code.slice(-1))-1].split("").map(Number)}if(e.code==="KeyS"&&cfg.kind==="builder"){state.game.saved=state.game.grid.join("")}if(e.code==="KeyN"&&cfg.kind==="procedural")makeProcedural("MEADOW-"+Math.floor(Math.random()*999));if(e.code==="KeyC"&&cfg.kind==="procedural")navigator.clipboard?.writeText(state.game.seed);if(e.code==="KeyK"&&cfg.kind==="remap")state.game.remap="dash";if(e.code==="KeyL"&&cfg.kind==="remap")state.game.remap="interact";if(e.code===state.game.dashKey&&cfg.kind==="remap"){const p=state.game.p;p.x=clamp(p.x+60,56,1040);addLog("Dash via "+e.code)}if(e.code==="Space"&&cfg.kind==="ai"){state.game.bell=2.4;addLog("Bell rang; AI investigates.")}if(e.code==="KeyF"&&cfg.kind==="ai")state.game.lamp=!state.game.lamp;if(e.code==="KeyO"&&cfg.kind==="performance")state.game.optimized=!state.game.optimized;if(e.code==="Space"&&cfg.kind==="kit"&&state.game.ability<=0){state.game.ability=3;state.game.components.unshift("Ability module fired.")}}
window.addEventListener("keydown",e=>{if(!e.repeat)onKey(e,false)});window.addEventListener("keyup",e=>onKey(e,true));
canvas.addEventListener("pointermove",e=>{const r=canvas.getBoundingClientRect();pointer.x=(e.clientX-r.left)*W/r.width;pointer.y=(e.clientY-r.top)*H/r.height});
canvas.addEventListener("pointerdown",e=>{pointer.down=true;const r=canvas.getBoundingClientRect();click((e.clientX-r.left)*W/r.width,(e.clientY-r.top)*H/r.height)});
canvas.addEventListener("pointerup",()=>pointer.down=false);
function frame(ts){const dt=Math.min(.05,(ts-last)/1000||0);last=ts;update(dt);render();requestAnimationFrame(frame)}
window.render_game_to_text=()=>JSON.stringify({project:"GDV502-P"+cfg.n,id:"GDV502-P"+cfg.n,title:cfg.title,mode:state.mode,score:Math.round(state.score),message:state.message,game:state.game,log:state.log,coordinateSystem:"1120x700 canvas, origin top-left"});
window.advanceTime=(ms)=>{const steps=Math.max(1,Math.round(ms/16.667));for(let i=0;i<steps;i++)update(1/60);render()};
render();requestAnimationFrame(frame);